### PR TITLE
Add label option to Marker

### LINKED ISSUE #69: Missing marker option 'label'
This important option is missing

### PR DESCRIPTION
**Pull request by thiagotalma**
Fix #69

### CODE REVIEW

**Comment by thiagotalma** [comment]
Hello @tonydspaniard 
Can you take a look at this?
It's a very simple PR but the lack of this label is preventing me from using the extension.
Thanks!

**Comment by tonydspaniard** [comment]
I'll add a version patch as soon as I get in front of the keyboard

**Comment by thiagotalma** [comment]
> I'll add a version patch as soon as I get in front of the keyboard

@tonydspaniard I think you forgot....   😉

**Comment by tonydspaniard** [comment]
done sorry :)

**Pull request merged**
